[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/studio"
  to = "/studio.html"
  status = 200

[[redirects]]
  from = "/s/:id/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/s/:id"
  to = "/index.html"
  status = 200
